In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
import os
import sys

In [2]:
# get the absolute path of the current file
current_dir = os.path.dirname(os.path.abspath("__file__"))
# get the project root (one level up from notebooks/)
project_root = os.path.abspath(os.path.join(current_dir, ".."))
# add project root to sys.path
if project_root not in sys.path:
    sys.path.append(project_root)

In [3]:
%reload_ext autoreload
%autoreload 2

from utils.stock_utils import fetch_financial_data, fetch_ohlcv_data
from utils.kpi import CAGR, volatility, Sharpe, max_dd, Sortino, calamar, jensens_alpha
from utils.technical_indicators import ATR

In [4]:
nifty_top_20 = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "AXISBANK.NS", 
    "TCS.NS", "LT.NS", "BHARTIARTL.NS", "SBIN.NS", "ITC.NS", 
    "HINDUNILVR.NS", "BAJFINANCE.NS", "KOTAKBANK.NS", "MARUTI.NS", "M&M.NS", 
    "TATASTEEL.NS", "SUNPHARMA.NS", "HCLTECH.NS", "ADANIENT.NS", "NTPC.NS"
]

In [5]:
financial_data = fetch_financial_data(nifty_top_20)

--- All downloads complete ---

In [7]:
financial_data['RELIANCE.NS']['financials']

,2025-03-31,2024-03-31,2023-03-31,2022-03-31,2021-03-31
Tax Effect Of Unusual Items,3.339140e+09,4.065480e+09,-3.185730e+09,8.188344e+09,NaN
Tax Rate For Calcs,2.380000e-01,2.455000e-01,2.185000e-01,2.004000e-01,NaN
Normalized EBITDA,1.798710e+12,1.752880e+12,1.547650e+12,1.222880e+12,NaN
Total Unusual Items,1.403000e+10,1.656000e+10,-1.458000e+10,4.086000e+10,NaN
Total Unusual Items Excluding Goodwill,1.403000e+10,1.656000e+10,-1.458000e+10,4.086000e+10,NaN
Net Income From Continuing Operation Net Minority Interest,6.964800e+11,6.962100e+11,6.628400e+11,5.904400e+11,NaN
Reconciled Depreciation,5.313600e+11,5.083200e+11,4.030300e+11,2.978200e+11,NaN
Reconciled Cost Of Revenue,7.226870e+12,6.745990e+12,6.718980e+12,5.316780e+12,NaN
EBITDA,1.812740e+12,1.769440e+12,1.533070e+12,1.263740e+12,NaN
EBIT,1.281380e+12,1.261120e+12,1.130040e+12,9.659200e+11,NaN
Net Interest Income,-1.000100e+11,-1.119000e+11,-7.842000e+10,-1.926000e+10,NaN
Interest Expense,2.212100e+11,2.177200e+11,1.895800e+11,1.443800e+11,NaN
Interest Income,1.241000e+11,1.074500e+11,1.124000e+11,1.252900e+11,NaN
Normalized Income,6.857891e+11,6.837155e+11,6.742343e+11,5.577683e+11,NaN
Net Income From Continuing And Discontinued Operation,6.964800e+11,6.962100e+11,6.670200e+11,6.070500e+11,NaN
Total Expenses,8.522310e+12,7.893980e+12,7.758200e+12,6.172000e+12,NaN
Rent Expense Supplemental,2.779000e+10,7.150000e+09,8.440000e+09,6.260000e+09,NaN
Diluted Average Shares,1.353241e+10,1.353248e+10,1.353231e+10,1.353231e+10,NaN
Basic Average Shares,1.353209e+10,1.353162e+10,1.353110e+10,1.353110e+10,NaN
Diluted EPS,5.147000e+01,5.145000e+01,4.929500e+01,4.543000e+01,NaN
Basic EPS,5.147000e+01,5.145000e+01,4.929500e+01,4.600000e+01,NaN
Diluted NI Availto Com Stockholders,6.964800e+11,6.962100e+11,6.670200e+11,6.070500e+11,NaN
Net Income Common Stockholders,6.964800e+11,6.962100e+11,6.670200e+11,6.070500e+11,NaN
Otherunder Preferred Stock Dividend,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Net Income,6.964800e+11,6.962100e+11,6.670200e+11,6.070500e+11,NaN
Minority Interests,-1.166100e+11,-9.399000e+10,-7.386000e+10,-7.140000e+10,NaN
Net Income Including Noncontrolling Interests,8.130900e+11,7.902000e+11,7.408800e+11,6.784500e+11,NaN
Net Income Discontinuous Operations,NaN,0.000000e+00,4.180000e+09,1.661000e+10,NaN
Net Income Continuous Operations,8.130900e+11,7.902000e+11,7.367000e+11,6.618400e+11,NaN
Tax Provision,2.523000e+11,2.570700e+11,2.037600e+11,1.597000e+11,NaN
Pretax Income,1.060170e+12,1.043400e+12,9.404600e+11,8.215400e+11,NaN
Other Non Operating Income Expenses,3.507000e+10,3.302000e+10,1.758000e+10,1.024000e+10,NaN
Special Income Charges,-1.540000e+09,-2.650000e+09,-1.560000e+09,2.737000e+10,NaN
Other Special Charges,1.540000e+09,2.650000e+09,1.560000e+09,-2.737000e+10,NaN
Write Off,NaN,NaN,NaN,0.000000e+00,1.210000e+09
Net Non Operating Interest Income Expense,-1.000100e+11,-1.119000e+11,-7.842000e+10,-1.926000e+10,NaN
Total Other Finance Cost,2.900000e+09,1.630000e+09,1.240000e+09,1.700000e+08,NaN
Interest Expense Non Operating,2.212100e+11,2.177200e+11,1.895800e+11,1.443800e+11,NaN
Interest Income Non Operating,1.241000e+11,1.074500e+11,1.124000e+11,1.252900e+11,NaN
Operating Income,1.124620e+12,1.116660e+12,1.020150e+12,7.876300e+11,NaN
Operating Expense,1.295440e+12,1.147990e+12,1.039220e+12,8.552200e+11,NaN
Other Operating Expenses,6.319200e+11,5.304500e+11,4.773500e+11,4.209000e+11,NaN
Selling General And Administration,3.802600e+11,3.714200e+11,3.167300e+11,2.482500e+11,NaN
Selling And Marketing Expense,2.160100e+11,2.098900e+11,1.973600e+11,1.594200e+11,NaN
General And Administrative Expense,1.642500e+11,1.615300e+11,1.193700e+11,8.883000e+10,NaN
Rent And Landing Fees,2.623000e+10,6.010000e+09,7.290000e+09,5.780000e+09,NaN
Gross Profit,2.420060e+12,2.264650e+12,2.059370e+12,1.642850e+12,NaN
Cost Of Revenue,7.226870e+12,6.745990e+12,6.718980e+12,5.316780e+12,NaN
Total Revenue,9.646930e+12,9.010640e+12,8.778350e+12,6.959630e+12,NaN
Operating Revenue,9.646930e+12,9.010640e+12,8.778350e+12,6.959630e+12,NaN

In [59]:
pd.set_option('display.max_rows', None)
financial_data['RELIANCE.NS']['balance_sheet']

,2025-03-31,2024-03-31,2023-03-31,2022-03-31,2021-03-31
Ordinary Shares Number,1.353287e+10,1.353222e+10,1.353219e+10,1.353199e+10,NaN
Share Issued,1.353287e+10,1.353222e+10,1.353219e+10,1.353199e+10,NaN
Net Debt,2.468850e+12,2.310820e+12,2.798100e+12,2.327960e+12,NaN
Total Debt,3.695750e+12,3.461420e+12,3.343920e+12,2.819740e+12,NaN
Tangible Book Value,4.342610e+12,4.331070e+12,3.850770e+12,5.476870e+12,NaN
Invested Capital,1.190730e+13,1.118103e+13,1.029838e+13,1.045790e+13,NaN
Working Capital,4.553300e+11,7.273300e+11,2.955300e+11,3.835700e+11,NaN
Net Tangible Assets,4.342610e+12,4.331070e+12,3.850770e+12,5.476870e+12,NaN
Capital Lease Obligations,2.204500e+11,2.152000e+11,2.042600e+11,1.566900e+11,NaN
Common Stock Equity,8.432000e+12,7.934810e+12,7.158720e+12,7.794850e+12,NaN
Total Capitalization,1.080099e+13,1.016193e+13,8.990480e+12,9.671840e+12,NaN
Total Equity Gross Minority Interest,1.009626e+13,9.257880e+12,8.288810e+12,8.889840e+12,NaN
Minority Interest,1.664260e+12,1.323070e+12,1.130090e+12,1.094990e+12,NaN
Stockholders Equity,8.432000e+12,7.934810e+12,7.158720e+12,7.794850e+12,NaN
Other Equity Interest,7.900000e+09,7.800000e+09,6.460000e+09,4.340000e+09,NaN
Retained Earnings,3.919430e+12,3.397870e+12,2.957390e+12,2.479510e+12,NaN
Additional Paid In Capital,9.314800e+11,9.984600e+11,9.983600e+11,1.148460e+12,NaN
Capital Stock,1.353200e+11,6.766000e+10,6.766000e+10,6.765000e+10,NaN
Common Stock,1.353200e+11,6.766000e+10,6.766000e+10,6.765000e+10,NaN
Total Liabilities Net Minority Interest,9.404930e+12,8.301980e+12,7.785500e+12,6.106810e+12,NaN
Total Non Current Liabilities Net Minority Interest,4.867580e+12,4.328310e+12,3.828070e+12,3.020190e+12,NaN
Other Non Current Liabilities,1.100510e+12,1.127520e+12,1.137660e+12,3.779200e+11,NaN
Tradeand Other Payables Non Current,1.090900e+11,5.667000e+10,7.704000e+10,1.202400e+11,NaN
Non Current Deferred Taxes Liabilities,8.345300e+11,7.224100e+11,6.032400e+11,4.964400e+11,NaN
Long Term Debt And Capital Lease Obligation,2.540410e+12,2.401270e+12,1.994060e+12,2.007060e+12,NaN
Long Term Capital Lease Obligation,1.714200e+11,1.741500e+11,1.623000e+11,1.300700e+11,NaN
Long Term Debt,2.368990e+12,2.227120e+12,1.831760e+12,1.876990e+12,NaN
Long Term Provisions,2.830400e+11,2.044000e+10,1.607000e+10,1.853000e+10,NaN
Current Liabilities,4.537370e+12,3.973670e+12,3.957430e+12,3.086620e+12,NaN
Other Current Liabilities,2.000000e+07,2.000000e+07,2.000000e+07,2.158400e+11,NaN
Current Debt And Capital Lease Obligation,1.155340e+12,1.060150e+12,1.349860e+12,8.126800e+11,NaN
Current Capital Lease Obligation,4.903000e+10,4.105000e+10,4.196000e+10,2.662000e+10,NaN
Current Debt,1.106310e+12,1.019100e+12,1.307900e+12,7.860600e+11,NaN
Current Provisions,4.147000e+10,2.175000e+10,2.178000e+10,1.936000e+10,NaN
Payables,2.710490e+12,2.613090e+12,2.353090e+12,2.232840e+12,NaN
Other Payable,8.409100e+11,8.276200e+11,8.795000e+11,6.375200e+11,NaN
Dividends Payable,NaN,1.700000e+09,1.870000e+09,2.020000e+09,2.080000e+09
Accounts Payable,1.867890e+12,1.783770e+12,1.471720e+12,1.593300e+12,NaN
Total Assets,1.950121e+13,1.755986e+13,1.607431e+13,1.499665e+13,NaN
Total Non Current Assets,1.450851e+13,1.285886e+13,1.182135e+13,1.152646e+13,NaN
Other Non Current Assets,3.719700e+11,2.678400e+11,2.578300e+11,4.337000e+11,NaN
Non Current Prepaid Assets,1.235400e+11,7.764000e+10,8.390000e+10,9.626000e+10,NaN
Non Current Deferred Taxes Assets,4.080000e+09,9.380000e+09,1.549000e+10,1.043000e+10,NaN
Investmentin Financial Assets,1.135860e+12,1.035610e+12,1.054600e+12,1.795940e+12,NaN
Available For Sale Securities,1.029840e+12,9.802400e+11,1.002500e+12,1.746820e+12,NaN
Financial Assets Designatedas Fair Value Through Profitor Loss Total,1.060200e+11,5.537000e+10,5.210000e+10,4.912000e+10,NaN
Long Term Equity Investment,1.568300e+11,1.807300e+11,1.364600e+11,1.084090e+12,NaN
Investmentsin Joint Venturesat Cost,9.067000e+10,1.014100e+11,6.211000e+10,2.633000e+10,NaN
Investmentsin Associatesat Cost,6.616000e+10,7.932000e+10,7.435000e+10,1.057760e+12,NaN
Goodwill And Other Intangible Assets,4.089390e+12,3.603740e+12,3.307950e+12,2.317980e+12,NaN
Other Intangible Assets,3.844090e+12,3.453850e+12,3.155250e+12,2.187890e+12,NaN
Goodwill,2.453000e+11,1.498900e+11,1.527000e+11,1.300900e+11,NaN
Net PPE,8.619420e+12,7.674930e+12,6.949870e+12,5.772180e+12,NaN
Accumulated Depreciation,-2.821570e+12,-2.499930e+12,-2.240410e+12,-1.964830e+12,NaN
Gross PPE,8.528120e+12,1.017486e+13,9.190280e+12,7.737010e+12,NaN
Construction In Progress,1.788400e+12,1.614090e+12,1.244840e+12,7.676400e+11,NaN
Other Properties,9.528300e+11,8.876000e+11,7.074400e+11,5.114900e+11,NaN
Machinery Furniture Equipment,6.615370e+12,5.979680e+12,5.743560e+12,5.283720e+12,NaN
Buildings And Improvements,1.063510e+12,8.206200e+11,6.974700e+11,4.756100e+11,NaN
Land And Improvements,1.020880e+12,8.728700e+11,7.969700e+11,6.985500e+11,NaN
Properties,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Current Assets,4.992700e+12,4.701000e+12,4.252960e+12,3.470190e+12,NaN
Other Current Assets,2.006900e+11,1.465100e+11,1.208400e+11,1.593700e+11,NaN
Restricted Cash,5.857000e+10,3.685000e+10,3.450800e+11,2.669000e+10,NaN
Prepaid Assets,4.118700e+11,5.353900e+11,4.883900e+11,4.396500e+11,NaN
Inventory,1.460620e+12,1.527700e+12,1.400080e+12,1.077780e+12,NaN
Other Inventories,1.172800e+11,1.021000e+11,5.891000e+10,2.681000e+10,NaN
Finished Goods,5.030500e+11,5.280000e+11,5.453900e+11,4.127000e+11,NaN
Work In Process,6.018900e+11,5.893600e+11,5.128200e+11,3.398500e+11,NaN
Raw Materials,2.384000e+11,3.082400e+11,2.829600e+11,2.984200e+11,NaN
Other Receivables,5.182000e+10,2.517000e+10,1.760000e+09,1.300000e+09,NaN
Accounts Receivable,4.212100e+11,3.162800e+11,2.844800e+11,2.364000e+11,NaN
Cash Cash Equivalents And Short Term Investments,2.387920e+12,2.113100e+12,1.612330e+12,1.529000e+12,NaN
Other Short Term Investments,1.381470e+12,1.177700e+12,1.270770e+12,1.193910e+12,NaN
Cash And Cash Equivalents,1.006450e+12,9.354000e+11,3.415600e+11,3.350900e+11,NaN
Cash Equivalents,5.416000e+11,1.952800e+11,3.018400e+11,2.468900e+11,NaN
Cash Financial,4.648500e+11,7.401200e+11,3.972000e+10,8.820000e+10,NaN

In [13]:

financial_data['RELIANCE.NS']['cash_flow']

,2025-03-31,2024-03-31,2023-03-31,2022-03-31,2021-03-31
Free Cash Flow,3.873600e+11,5.905000e+10,-2.595600e+11,1.050900e+11,NaN
Repayment Of Debt,-3.175500e+11,-3.505500e+11,-2.905900e+11,-4.064700e+11,NaN
Issuance Of Debt,2.637800e+11,6.961000e+11,3.593600e+11,5.934300e+11,NaN
Issuance Of Capital Stock,2.200000e+08,7.000000e+07,4.000000e+08,3.976700e+11,NaN
Capital Expenditure,-1.399670e+12,-1.528830e+12,-1.409880e+12,-1.001450e+12,NaN
End Cash Position,1.065020e+12,9.722500e+11,6.866400e+11,3.617800e+11,NaN
Other Cash Adjustment Outside Changein Cash,NaN,7.200000e+09,-1.766000e+10,9.410000e+09,2.400000e+08
Beginning Cash Position,9.722500e+11,6.866400e+11,3.617800e+11,1.739700e+11,NaN
Changes In Cash,9.277000e+10,2.856100e+11,3.425200e+11,1.784000e+11,NaN
Financing Cash Flow,-3.189100e+11,-1.664600e+11,1.045500e+11,1.728900e+11,NaN
Net Other Financing Charges,NaN,1.983000e+11,4.790000e+09,4.500000e+09,1.956820e+12
Interest Paid Cff,-4.102400e+11,-3.717300e+11,-2.165000e+11,-2.634900e+11,NaN
Cash Dividends Paid,-6.766000e+10,-6.089000e+10,-5.083000e+10,-4.297000e+10,NaN
Net Common Stock Issuance,2.200000e+08,7.000000e+07,4.000000e+08,3.976700e+11,NaN
Common Stock Issuance,2.200000e+08,7.000000e+07,4.000000e+08,3.976700e+11,NaN
Net Issuance Payments Of Debt,1.924700e+11,9.262000e+10,3.807500e+11,9.850000e+10,NaN
Net Short Term Debt Issuance,2.462400e+11,-2.529300e+11,3.119800e+11,-8.846000e+10,NaN
Net Long Term Debt Issuance,-5.377000e+10,3.455500e+11,6.877000e+10,1.869600e+11,NaN
Long Term Debt Payments,-3.175500e+11,-3.505500e+11,-2.905900e+11,-4.064700e+11,NaN
Long Term Debt Issuance,2.637800e+11,6.961000e+11,3.593600e+11,5.934300e+11,NaN
Investing Cash Flow,-1.375350e+12,-1.135810e+12,-9.123500e+11,-1.101030e+12,NaN
Net Other Investing Changes,-4.574000e+10,-4.423000e+10,NaN,-1.930600e+11,-2.000000e+07
Interest Received Cfi,1.583300e+11,1.064800e+11,1.110300e+11,5.933000e+10,NaN
Dividends Received Cfi,6.120000e+09,7.500000e+08,2.000000e+08,1.900000e+08,NaN
Net Investment Purchase And Sale,-1.178200e+11,1.769500e+11,2.944400e+11,2.590000e+09,NaN
Sale Of Investment,6.725580e+12,5.313550e+12,5.012660e+12,6.681370e+12,NaN
Purchase Of Investment,-6.843400e+12,-5.136600e+12,-4.718220e+12,-6.678780e+12,NaN
Net PPE Purchase And Sale,2.343000e+10,1.530700e+11,9.186000e+10,3.137000e+10,NaN
Sale Of PPE,2.343000e+10,1.530700e+11,9.186000e+10,3.137000e+10,NaN
Purchase Of PPE,NaN,NaN,NaN,-1.001450e+12,-1.058370e+12
Capital Expenditure Reported,-1.399670e+12,-1.528830e+12,-1.409880e+12,-1.001450e+12,NaN
Operating Cash Flow,1.787030e+12,1.587880e+12,1.150320e+12,1.106540e+12,NaN
Taxes Refund Paid,-1.192500e+11,-1.196100e+11,-6.297000e+10,-3.797000e+10,NaN
Change In Working Capital,2.372400e+11,6.366000e+10,-1.963400e+11,7.250000e+09,NaN
Change In Payable,3.842700e+11,3.479600e+11,-6.000000e+09,3.988800e+11,NaN
Change In Inventory,3.134000e+10,-1.275600e+11,-3.222800e+11,-2.498300e+11,NaN
Change In Receivables,-1.783700e+11,-1.567400e+11,1.319400e+11,-1.418000e+11,NaN
Other Non Cash Items,1.000100e+11,1.119000e+11,7.958000e+10,2.336000e+10,NaN
Provisionand Write Offof Assets,NaN,NaN,0.000000e+00,3.600000e+08,5.300000e+08
Deferred Tax,NaN,NaN,NaN,0.000000e+00,-1.557000e+11
Depreciation And Amortization,5.313600e+11,5.083200e+11,4.030300e+11,2.978200e+11,NaN
Depreciation,5.313600e+11,5.083200e+11,4.030300e+11,2.978200e+11,NaN
Gain Loss On Investment Securities,-2.061000e+10,-2.010000e+10,1.176000e+10,-1.393000e+10,NaN
Net Foreign Currency Exchange Gain Loss,-3.240000e+09,-1.470000e+09,-3.191000e+10,1.950000e+10,NaN
Gain Loss On Sale Of PPE,1.350000e+09,1.780000e+09,-6.000000e+08,4.000000e+08,NaN
Gain Loss On Sale Of Business,NaN,NaN,0.000000e+00,-2.872000e+10,-8.500000e+09
Net Income From Continuing Operations,1.060170e+12,1.043400e+12,9.480100e+11,8.414200e+11,NaN

In [ ]:

financial_data['RELIANCE.NS']['info']

{'address1': 'Maker Chambers IV',
 'address2': '3rd Floor 222 Nariman Point',
 'city': 'Mumbai',
 'zip': '400021',
 'country': 'India',
 'phone': '91 22 3555 5000',
 'fax': '91 22 2204 2268',
 'website': 'https://www.ril.com',
 'industry': 'Oil & Gas Refining & Marketing',
 'industryKey': 'oil-gas-refining-marketing',
 'industryDisp': 'Oil & Gas Refining & Marketing',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Reliance Industries Limited engages in the hydrocarbon exploration and production, oil and chemicals, retail, and digital service businesses worldwide. It operates through Oil to Chemicals, Oil and Gas, Retail, Digital Services, and Others segments. The company offers refining and marketing products, including liquefied petroleum gas, propylene, naphtha, gasoline, jet/aviation turbine fuel, kerosine oil, diesel, sulphur, and petroleum coke. It also provides polymers, including high-density and low-density polyethylene (PE), linear low-density PE, homopolymer, random and impact copolymer, and polyvinyl chloride; fibre intermediates, such as purified terephthalic acid, and ethylene glycols and oxide; aromatics, such as paraxylene, ortho xylene, benzene, and linear alkyl benzene and paraffin; and textiles comprising fabrics, apparel, and auto furnishings. In addition, the company offers elastomers, such as polybutadiene rubber, styrene butadiene rubber, and butyl rubber; fibre and yarn polyesters; and bioenergy solutions, consisting of compressed biogas, and pellets and briquettes. Further, it engages in oil and gas exploration and production activities; and operates various stores comprising supermarket, hypermarket, wholesale cash and carry, specialty, and online stores, as well as stores that offer apparel, beauty and cosmetics, accessories, footwear, consumer electronics, and others. Additionally, the company operates media and entertainment platforms, and Network18 and television channels; publishes magazines; and offers highway hospitality and fleet management services. It also provides digital services, including connectivity, fibre, mobile devices, apps, business, and other digital solutions. The company was founded in 1957 and is based in Mumbai, India.',
 'fullTimeEmployees': 403303,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Mukesh Dhirubhai Ambani',
   'age': 68,
   'title': 'Chairman & MD',
   'yearBorn': 1957,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nikhil Rasiklal Meswani',
   'age': 59,
   'title': 'Executive Director',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hital Rasiklal Meswani',
   'age': 57,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2025,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Panda Madhusudana Siva Prasad',
   'age': 73,
   'title': 'Executive Director',
   'yearBorn': 1952,
   'fiscalYear': 2025,
   'totalPay': 199600000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anant Mukesh Ambani',
   'title': 'Whole-Time Director',
   'fiscalYear': 2025,
   'totalPay': 23100000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Parul  Sharma',
   'title': 'Group President',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Srikanth  Venkatachari',
   'age': 59,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mahesh  Marve',
   'title': 'Head of Technology',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hemen Kanu Modi',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Savithri  Parekh',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 10,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 10,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://ril.com/html/investor/investor.html',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1397.6,
 'open': 1397.2,
 'dayLow': 1397.2,
 'dayHigh': 1412.9,
 'regularMarketPreviousClose': 1397.6,
 'regularMarketOpen': 1397.2,
 'regularMarketDayLow': 1397.2,
 'regularMarketDayHigh': 1412.9,
 'dividendRate': 5.5,
 'dividendYield': 0.39,
 'exDividendDate': 1755129600,
 'payoutRatio': 0.08939999,
 'fiveYearAvgDividendYield': 0.44,
 'beta': 0.205,
 'trailingPE': 22.94682,
 'forwardPE': 21.527166,
 'volume': 6604096,
 'regularMarketVolume': 6604086,
 'averageVolume': 13582443,
 'averageVolume10days': 22260527,
 'averageDailyVolume10Day': 22260527,
 'bid': 1410.9,
 'ask': 1410.6,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 19094319398912,
 'nonDilutedMarketCap': 18912983753278,
 'fiftyTwoWeekLow': 1114.85,
 'fiftyTwoWeekHigh': 1611.8,
 'allTimeHigh': 1611.8,
 'allTimeLow': 5.428648,
 'priceToSalesTrailing12Months': 1.8635501,
 'fiftyDayAverage': 1416.416,
 'twoHundredDayAverage': 1448.278,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'tradeable': False,
 'enterpriseValue': 22151887323136,
 'profitMargins': 0.08122,
 'floatShares': 6606391655,
 'sharesOutstanding': 13532472634,
 'heldPercentInsiders': 0.51049,
 'heldPercentInstitutions': 0.27975,
 'impliedSharesOutstanding': 13532472635,
 'bookValue': 648.12,
 'priceToBook': 2.177066,
 'lastFiscalYearEnd': 1743379200,
 'nextFiscalYearEnd': 1774915200,
 'mostRecentQuarter': 1767139200,
 'earningsQuarterlyGrowth': 0.006,
 'netIncomeToCommon': 832110002176,
 'trailingEps': 61.49,
 'forwardEps': 65.54509,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1730073600,
 'enterpriseToRevenue': 2.162,
 'enterpriseToEbitda': 13.15,
 '52WeekChange': 0.12063503,
 'SandP52WeekChange': 0.18339145,
 'lastDividendValue': 5.5,
 'lastDividendDate': 1755129600,
 'quoteType': 'EQUITY',
 'currentPrice': 1410.9,
 'targetHighPrice': 2020.0,
 'targetLowPrice': 1370.0,
 'targetMeanPrice': 1717.1111,
 'targetMedianPrice': 1700.0,
 'recommendationMean': 1.45714,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 36,
 'totalCash': 2238710022144,
 'totalCashPerShare': 165.457,
 'ebitda': 1684509949952,
 'totalDebt': 3745930018816,
 'totalRevenue': 10245479858176,
 'debtToEquity': 35.651,
 'revenuePerShare': 757.082,
 'grossProfits': 3665570037760,
 'earningsGrowth': 0.006,
 'revenueGrowth': 0.104,
 'grossMargins': 0.35777,
 'ebitdaMargins': 0.16441,
 'operatingMargins': 0.11852,
 'financialCurrency': 'INR',
 'symbol': 'RELIANCE.NS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Free Realtime Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'longName': 'Reliance Industries Limited',
 'marketState': 'REGULAR',
 'shortName': 'RELIANCE INDUSTRIES LTD',
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 820467900000,
 'regularMarketChange': 13.400024,
 'regularMarketDayRange': '1397.2 - 1412.9',
 'fullExchangeName': 'NSE',
 'averageDailyVolume3Month': 13582443,
 'fiftyTwoWeekLowChange': 296.15002,
 'fiftyTwoWeekLowChangePercent': 0.26564115,
 'fiftyTwoWeekRange': '1114.85 - 1611.8',
 'fiftyTwoWeekHighChange': -200.80005,
 'fiftyTwoWeekHighChangePercent': -0.12458124,
 'fiftyTwoWeekChangePercent': 12.063503,
 'earningsTimestamp': 1768557600,
 'earningsTimestampStart': 1777024800,
 'earningsTimestampEnd': 1777024800,
 'earningsCallTimestampStart': 1745592300,
 'earningsCallTimestampEnd': 1745592300,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 61.49,
 'epsForward': 65.54509,
 'epsCurrentYear': 59.31711,
 'priceEpsCurrentYear': 23.787403,
 'fiftyDayAverageChange': -5.4160156,
 'fiftyDayAverageChangePercent': -0.0038237465,
 'twoHundredDayAverageChange': -37.277954,
 'twoHundredDayAverageChangePercent': -0.025739502,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'corporateActions': [],
 'regularMarketTime': 1773824314,
 'exchange': 'NSI',
 'messageBoardId': 'finmb_878373',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.9588568,
 'regularMarketPrice': 1411.0,
 'averageAnalystRating': '1.5 - Strong Buy',
 'cryptoTradeable': False,
 'trailingPegRatio': None}

In [ ]:
total_cash = financial_data['RELIANCE.NS']['info'].get('totalCash')
total_debt = financial_data['RELIANCE.NS']['info'].get('totalDebt')
market_cap = financial_data['RELIANCE.NS']['info'].get('marketCap')
EBIT = financial_data['RELIANCE.NS']['financials'].loc['EBIT'].iloc[0]

#Earnings Yield: EBIT/EnterpriseValue. (Enterprise Value = Market Cap + Debt - Cash).

In [61]:
#Return on Capital: EBIT/(FixedAssets+WorkingCapital)
# Fixed Assets = Net PPE, Working Capital = current_assets - current_liabilities

fixed_assets = financial_data['RELIANCE.NS']['balance_sheet'].loc['Net PPE'].iloc[0]
total_assets = financial_data['RELIANCE.NS']['balance_sheet'].loc['Total Assets'].iloc[0]
current_assets = financial_data['RELIANCE.NS']['balance_sheet'].loc['Current Assets'].iloc[0]
current_liabilities = financial_data['RELIANCE.NS']['balance_sheet'].loc['Current Liabilities'].iloc[0]

2025-03-31    1.950121e+13
2024-03-31    1.755986e+13
2023-03-31    1.607431e+13
2022-03-31    1.499665e+13
2021-03-31             NaN
Name: Total Assets, dtype: float64